version: "3"
services:
  cowrie:
    hostname: cowrie
    image: cowrie/cowrie
    ports:
      - "22:22"
    volumes:
      - ./cowrie/config/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg
      - ./cowrie/config/userdb.txt:/cowrie/cowrie-git/etc/userdb.txt
      - ./cowrie/log/cowrie.json:/cowrie/cowrie-git/var/log/cowrie/cowrie.json
  elasticsearch:
    hostname: elasticsearch
    image: elasticsearch:8.5.3
    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      discovery.type: single-node
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - /Users/juli/elastic:/usr/share/elasticsearch/data
    networks:
      - elastic
  kibana:
    image: kibana:8.5.3
    hostname: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    volumes:
      - ./kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      - elasticsearch
    networks:
      - elastic
  logstash:
    image: logstash:8.5.3
    hostname: logstash
    ports:
      - "5044:5044"
    volumes: 
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    environment:
      LS_JAVA_OPTS: -Xms256m -Xmx256m
    depends_on:
      - elasticsearch
    networks:
      - elastic
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.5.3
    hostname: filebeat
    volumes:
      - ./cowrie/log/cowrie.json:/var/log/cowrie/cowrie.json
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - elasticsearch
    networks:
      - elastic

networks:
  elastic:
